### ISSUE TITLE
No module named 'reactivestreams' using Jupyter Notebook

### ISSUE THREAD

**Issue by CybeRCrab1** [rsocket/rsocket-py#45] opened 2022-04-12 09:57 UTC
## Expected Behavior

I am writing a project of making a rsocket client calling a java server to fetch data. The class Defaultsubscriber is needed so i import reactivestreams.subscriber in it. The client ran successfully in Pycharm. So i packaged my project, downloaded it and ran tests on Notebook.

## Actual Behavior

An error message: No module named 'reactivestreams' using Jupyter Notebook

## Steps to Reproduce

#In myproject.py file
from reactiestreams.subscriber import DefaultSubscriber

#In setup.cgf
zip_safe = True
include_package_data = True
packages = find:
install requires =
    pytest>=5.0.0
    betterproto
    aiohttp
    pandas
    rsocket>=3.0 dev3

#In notebook
from myproject import MyClient

ModuleNotFoundError: no module named 'reactivestreams'

## Your Environment

* RSocket version(s) used: 3.0 dev3
* Other relevant libraries versions (eg. `netty`, ...): 
* Python 3.8

**Comment by gabis-precog** [comment] 2022-04-12 10:03
could not reproduce using local jupyter notebook (6.4.10, python 3.10)
please specify version and how you run it (local ? venv s? container ?)
are you sure it is being installed in the environment of the notebook (please attach install log)

**Comment by gabis-precog** [comment] 2022-04-23 20:24
closing. cannot reproduce.

**Closed by gabis-precog** 2022-04-23 20:24 UTC
